services:
  backend:
    image: bozemanpass/todo-backend:stack
    build: ./backend
    ports:
      - "5000:5000" # @stack http-proxy /api/todos
    environment:
      DB_HOST: ${STACK_SVC_DB:-db}
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todoapp
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: bozemanpass/todo-frontend:stack
    build: ./frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000}
    ports:
      - "3000:3000" # @stack http-proxy /

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    entrypoint: bash
    command: -c  'usermod -u ${STACK_HOST_UID:-1000} postgres;groupmod -g ${STACK_HOST_GID:-1000} postgres;exec /usr/local/bin/docker-entrypoint.sh postgres -c log_statement=all -c log_destination=stderr'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

