version: '3.8'
services:
  backend:
    image: bpi/todo-backend:stack
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${STACK_SVC_DB_HOST:-db}
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todoapp
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: bpi/todo-frontend:stack
    build: ./frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api/todos}
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
